name: rumahsehat_mobile
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  login_logout_registration:
    path: login_logout_registration

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  provider: ^6.0.1
  dropdown_button2: ^1.9.2
  flutter_datetime_picker: ^1.5.1
  flutter_bloc: ^8.1.1 # For state management
  equatable: ^2.0.5
  get_it: ^7.2.0 # For locator in repositories
  flutter_secure_storage: ^7.0.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true